name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. تثبيت Java (ضروري جداً للأندرويد)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 2. تثبيت Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. تثبيت Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 4. تثبيت المكاتب
      - name: Install Flet
        run: pip install flet yfinance

      # 5. بناء التطبيق
      - name: Build APK
        run: flet build apk --no-android-signing

      # 6. رفع الملف لك
      - uses: actions/upload-artifact@v4
        with:
          name: GoldApp
          path: build/apk/**/*.apk
